DATASET_PATH: "/home/jaspinder/.cache/kagglehub/datasets/mvtec-ad"
DATASET_OBJECTS:
  - bottle
  - cable
  - can # REC
  - capsule
  - carpet
  - fabric # REC
  - fruit_jelly
  - grid
  - hazelnut # REC
  - leather
  - metal_nut
  - pill
  - rice # REC
  - screw
  - sheet_metal
  - tile
  - toothbrush
  - transistor
  - vial
  - wallplugs # REC
  - walnuts # REC
  - wood
  - zipper

MODELS_CONFIG:
  base_autoencoder:
    model_name: "base_autoencoder_1"
    batch_size: 16
    num_epochs: 30
    validation_split: 0.1
    learning_rate: 1e-3

  ottthmane_demo:
    batch_size: 32
    num_epochs: 20
    
  sksksarlo_demo:
    batch_size: 64
    num_epochs: 15

